#!/bin/sh

# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

export PATH="$PATH:$HOME/scripts"
export EDITOR="vim"


if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi
